version: '3.3'
services:
  post_db:
    image: mongo:${mongo_db_version}
    volumes:
      - post_db:/data/db
    ports:
      - 27017:27017
    networks:
      back_end:
        aliases:
          - comment_db

  ui:
    build: ./ui
    image: ${USERNAME}/ui:${ui_version}
    environment:
      - POST_SERVICE_HOST=post
      - POST_SERVICE_PORT=5000
      - COMMENT_SERVICE_HOST=comment
      - COMMENT_SERVICE_PORT=9291
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    depends_on:
      - post
    ports:
      - ${http_port}:9292
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      - front_end

  post:
    build: ./post-py
    image: ${USERNAME}/post:${post_version}
    depends_on:
      - post_db
    ports:
      - 5000:5000
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
    networks:
      - back_end
      - front_end

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${comment_version}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - 9291:9292
    networks:
      - back_end
      - front_end

  prometheus:
    image: ${USERNAME}/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=1d'
    networks:
      - back_end
      - front_end

  node-exporter:
    image: prom/node-exporter
    user: root
    networks:
      - back_end
    ports:
      - 9100:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'

  mongo-exporter:
    image: percona/mongodb_exporter:${mongo_exporter_ver}
    ports:
      - 9216:9216
    command:
      - '--mongodb.uri=mongodb://post_db:27017/admin?ssl=true'
    networks:
      - back_end

volumes:
  post_db:
  prometheus_data:

networks:
  back_end:
  front_end:
