---
- name: Gitlab in Docker
  hosts: gitlab
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: 
          - docker.io
          - docker-compose
        state: present

    - name: Make dir gitlab config
      file:
        state: directory
        path: /srv/gitlab/config

    - name: Make dir gitlab data
      file:
        state: directory
        path: /srv/gitlab/data

    - name: Make dir gitlab logs
      file:
        state: directory
        path:  /srv/gitlab/logs

    - name: Copy docker-compose
      copy:
        src: ../files/docker-compose.yml
        dest: /srv/gitlab/docker-compose.yml
    
    - name: Compose UP
      docker_compose:
        project_src: /srv/gitlab
        state: present
        restarted: yes
        services:
          - web

    - name: Pause before going further
      pause:
        minutes: 3

    - name: Lookup initial root password
      command: docker exec gitlab_web_1 cat /etc/gitlab/initial_root_password
      register: password_output
